-- selecting all players info from person and player table

SELECT *
FROM PERSON P1, PLAYER P2
WHERE P1.PERSON_ID=P2.PLAYER_ID;


--select a specific player info

SELECT *
FROM PERSON P1, PLAYER P2
WHERE (P1.PERSON_ID=P2.PLAYER_ID) AND P1.FIRST_NAME='David' AND LAST_NAME='Warner';

--selecting all umpires

SELECT * FROM PERSON P, UMPIRE U WHERE P.PERSON_ID=U.UMPIRE_ID;

--selecting specific umpire details

SELECT * FROM PERSON P, UMPIRE U WHERE (P.PERSON_ID=U.UMPIRE_ID) AND P.FIRST_NAME='Richard' AND P.LAST_NAME='Kettleborough';


--selecting all coach

SELECT * FROM PERSON P, COACH C WHERE (P.PERSON_ID=C.COACH_ID);

--GETTING THE NUMBER OF MATCH CONDUCTS BY A UMPIRE
SELECT UMPIRE_ID,COUNT(*)
FROM UMPIRE_MATCH
GROUP BY UMPIRE_ID
HAVING UMPIRE_ID='SA_Holdstock_27-04-70';

--GETTING HIGHEST WICKET MATCH ID IN A GROUND

SELECT M.MATCH_ID,PS.PLAYER_ID,NUM_OF_WICKETS
FROM MATCH M, PLAYER_SCORE PS
WHERE M.GROUND_ID='PAK_Lahore' AND PS.MATCH_ID=M.MATCH_ID AND
(
(M.MATCH_ID,PLAYER_ID)=ANY(
	SELECT M1.MATCH_ID,PLAYER_ID FROM MATCH M1, PLAYER_SCORE PS1 WHERE M1.GROUND_ID='PAK_Lahore' AND PS1.MATCH_ID=M1.MATCH_ID AND 
	NUM_OF_WICKETS=(SELECT MAX(NUM_OF_WICKETS) FROM MATCH M2, PLAYER_SCORE PS2 WHERE M2.GROUND_ID='PAK_Lahore' AND PS2.MATCH_ID=M2.MATCH_ID))
);

--GETTING SERIES NUM OF FOURS
SELECT SUM(NUM_OF_FOURS)
FROM PLAYER_SCORE PS, MATCH M
WHERE M.SERIES_ID='AUSENG_SEP_20' AND M.MATCH_ID=PS.MATCH_ID;


--TEAM SERIES
SELECT MIN(MATCH_DATE), MAX(MATCH_DATE)
FROM TEAM_MATCH TM,MATCH M
WHERE TM.MATCH_ID=M.MATCH_ID
GROUP BY SERIES_ID
HAVING SERIES_ID='AUSENG_SEP_20';


INSERT INTO GROUND VALUES('mirpur_dhaka_222','MIrPURstadium','dhaka','1223','1250','mipur.jpg');
DELETE FROM GROUND WHERE GROUND_ID='mirpur_dhaka_222';


--player details
SELECT * FROM PERSON P, PLAYER PL WHERE P.PERSON_ID=PL.PLAYER_ID;

--player scorecard
SELECT * FROM PLAYER_STAT PS, STAT S WHERE PLAYER_ID='AUS_Warner_27-10-86' AND PS.STAT_ID=S.STAT_ID;


--player played matches
SELECT * FROM PLAYER_SCORE WHERE PLAYER_ID='AUS_Warner_27-10-86';

--matches in series
SELECT * FROM SERIES S, MATCH M WHERE S.SERIES_ID=M.SERIES_ID AND S.SERIES_ID='AUSENG_SEP_20';


--update ground
--UPDATE GROUND SET NAME='Queens Park Oval' WHERE GROUND_ID='POS_Trinidad';



--HIGHEST SCORED RUNS BY A PLAYER IN A MATCH

SELECT * FROM PLAYER_SCORE WHERE SCORED_RUNS= ANY(SELECT SCORED_RUNS FROM PLAYER_SCORE WHERE SCORED_RUNS=(SELECT MAX(SCORED_RUNS) FROM PLAYER_SCORE));

--HIGHESH WICKETS IN A MATCH
SELECT * FROM PLAYER_SCORE WHERE NUM_OF_WICKETS=ANY(SELECT NUM_OF_WICKETS FROM PLAYER_SCORE WHERE NUM_OF_WICKETS=(SELECT MAX(NUM_OF_WICKETS) FROM PLAYER_SCORE));


--HIGHEST RUN IN A CAREER
SELECT * FROM PLAYER_STAT WHERE PLAYER_ID=ANY(SELECT PLAYER_ID FROM PLAYER_STAT WHERE SCORED_RUN=(SELECT MAX(SCORED_RUN)FROM PLAYER_STAT));


--HIGHEST WICKETS BY PLAYER IN A CAREER 

SELECT * FROM PLAYER_STAT WHERE PLAYER_ID=ANY(SELECT PLAYER_ID FROM PLAYER_STAT WHERE NUM_OF_WICKETS=(SELECT MAX(NUM_OF_WICKETS) FROM PLAYER_STAT));







--HIGHEST SCORED RUNS IN A MATCH
SELECT * FROM MATCH WHERE MATCH_ID=(SELECT MATCH_ID FROM PLAYER_SCORE GROUP BY MATCH_ID HAVING SUM(SCORED_RUNS)=(SELECT MAX(SUM(SCORED_RUNS)) FROM PLAYER_SCORE GROUP BY MATCH_ID));


--MAX WIN BY A TEAM

SELECT * FROM TEAM_STAT WHERE TEAM_ID=ANY(SELECT TEAM_ID FROM TEAM_STAT WHERE TOTAL_WIN=ANY(SELECT MAX(TOTAL_WIN) FROM TEAM_STAT));

--MAX LOSE BY A TEAM
SELECT * FROM TEAM_STAT WHERE TEAM_ID=ANY(SELECT TEAM_ID FROM TEAM_STAT WHERE TOTAL_LOSE=ANY(SELECT MAX(TOTAL_LOSE) FROM TEAM_STAT));






















